version: '4.2'
services:
  app:
    image: maxmcavalcanti/max-tech-app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_postgres_db
    secrets:
      - max-tech-secrets
    env_file:
      - ./secrets.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  max-tech-secrets:
    external: true
volumes:
  postgres_data:
