apiVersion: v1
kind: Namespace
metadata:
  name: minha-aplicacao

---

apiVersion: v1
kind: Secret
metadata:
  name: max-tech-secrets
  namespace: minha-aplicacao
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: dGVjaF9wb3N0Z3Jlc19kYg==

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: minha-aplicacao
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 5432  
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: minha-aplicacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_DB

---

apiVersion: v1
kind: Service
metadata:
  name: max-tech-app-service
  namespace: minha-aplicacao
spec:
  selector:
    app: max-tech-app  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-tech-app-deployment
  namespace: minha-aplicacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: max-tech-app
  template:
    metadata:
      labels:
        app: max-tech-app
    spec:
      containers:
      - name: max-tech-app
        image: maxmcavalcanti/max-tech-app:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: max-tech-secrets
              key: POSTGRES_DB
        - name: POSTGRES_HOST  
          value: postgres
        imagePullPolicy: Always
